version: 1.7.10-{build}
environment:
  MSYS: C:\msys64
  MINGW32: C:\msys64\mingw
  MINGW64: C:\msys64\mingw
  MSYSTEM: MINGW32
install:
- ps: >-
    if (!(Test-Path "$env:MINGW32")) {
      Invoke-WebRequest http://files.1f0.de/mingw/mingw-w64-gcc-5.2-stable-r16.7z -OutFile mingw.7z
      7z x mingw.7z -o"$env:MINGW32" -y > $null
    }

    if (!(Test-Path C:\msys64\usr\bin\yasm.exe)) {
      Invoke-WebRequest http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -OutFile C:\msys64\usr\bin\yasm.exe
    }

    git submodule -q update --init --recursive
cache: # timestamp test
- C:\msys64\mingw -> appveyor.yml
- C:\msys64\usr\bin\yasm.exe -> appveyor.yml
build_script:
- cmd: build.bat silent nocolors
test: off
deploy: off
